ClientWebsite/Controllers/BooksController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;

namespace WebSiteBanSach.Controllers
{
    public class BooksController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        public PartialViewResult BookNewiPartial()
        {
            return PartialView(book.GetTake3Sach().ToList());
        }
        public ViewResult BookDetail(int MaSach = 0)
        {

            Sach sach_detail = book.GetSachById(MaSach);
            if (sach_detail == null)
            {
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            ClientWebsite.BookService.ChuDe chude = book.GetChuDeById(Int32.Parse(sach_detail.MaChuDe.ToString()));
            ClientWebsite.BookService.NhaXuatBan nxb = book.GetNXBByID(Int32.Parse(sach_detail.MaNXB.ToString()));
            ViewBag.TenChuDe = chude.TenChuDe;
            ViewBag.NhaXuatBan = nxb.TenNXB;
            return View(sach_detail);
        }
        public ActionResult AllBooks(int? page)
        {
            int pageSize = 12;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(book.GetSachByMoi().OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }
    }
}

ClientWebsite/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;
using WebSiteBanSach.Models;
using ClientWebsite.OrderService;

namespace WebSiteBanSach.Controllers
{
    public class CartController : Controller
    {
        SachServiceClient sach_client = new SachServiceClient();
        ServiceDonHangClient dh = new ServiceDonHangClient();
        #region Giỏ hàng
        //Lấy giỏ hàng 
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                //Nếu giỏ hàng chưa tồn tại thì mình tiến hành khởi tao list giỏ hàng (sessionGioHang)
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        //Thêm giỏ hàng
        public ActionResult ThemGioHang(int iMaSach, string strURL)
        {
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy ra session giỏ hàng
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sách này đã tồn tại trong session[giohang] chưa
            GioHang sanpham = lstGioHang.Find(n => n.iMaSach == iMaSach);
            if (sanpham == null)
            {
                sanpham = new GioHang(iMaSach);
                //Add sản phẩm mới thêm vào list
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoLuong++;
                return Redirect(strURL);
            }
        }
        //Cập nhật giỏ hàng 
        public ActionResult CapNhatGioHang(int iMaSP, FormCollection f)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sp có tồn tại trong session["GioHang"]
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(f["txtSoLuong"].ToString());

            }
            return RedirectToAction("SuaGioHang");
        }
        //Xóa giỏ hàng
        public ActionResult XoaGioHang(int iMaSP)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaSach == iMaSP);

            }
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        //Xây dựng trang giỏ hàng
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);
        }
        //Tính tổng số lượng và tổng tiền
        //Tính tổng số lượng
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }
        //Tính tổng thành tiền
        private double TongTien()
        {
            double dTongTien = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.ThanhTien);
            }
            return dTongTien;
        }
        //tạo partial giỏ hàng
        public ActionResult CartPartial()
        {
            if (TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        //Xây dựng 1 view cho người dùng chỉnh sửa giỏ hàng
        public ActionResult SuaGioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);

        }
        #endregion
        #region Đặt hàng
        //Xây dựng chức năng đặt hàng
        [HttpPost]
        public ActionResult DatHang()
        {
            //Kiểm tra đăng đăng nhập
            if (Session["InforLogin"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //Kiểm tra giỏ hàng
            if (Session["GioHang"] == null)
            {
                RedirectToAction("Index", "Home");
            }
            //Thêm đơn hàng
            ClientWebsite.OrderService.DonHang ddh = new ClientWebsite.OrderService.DonHang();
            ClientWebsite.UserService.KhachHang kh = (ClientWebsite.UserService.KhachHang)Session["InforLogin"];
            List<GioHang> gh = LayGioHang();
            ddh.MaKH = kh.MaKH;
            ddh.NgayDat = DateTime.Now;
            ddh.NgayGiao = DateTime.Now.AddDays(2);
           
            if (dh.AddDonHang(ddh) != 0)
            {
                Session["TB"] = "Thành Công !";
            }
            //Thêm chi tiết đơn hàng
            double thanhtien = 0;
            foreach (var item in gh)
            {
                ClientWebsite.OrderService.ChiTietDonHang ctDH = new ClientWebsite.OrderService.ChiTietDonHang();
                ctDH.MaDonHang = ddh.MaDonHang;
                ctDH.MaSach = item.iMaSach;
                ctDH.SoLuong = item.iSoLuong;
                ctDH.DonGia = (decimal)item.dDonGia;
                dh.AddCTDonHang(ctDH);
                thanhtien = thanhtien + item.iSoLuong * item.dDonGia;

            }
            return RedirectToAction("GioHang");

        }
        #endregion
       
    }
}

ClientWebsite/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using ClientWebsite.BookService;
using System.Web.Mvc;
using PagedList;

namespace WebSiteBanSach.Controllers
{
    public class HomeController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        public ActionResult Index(int? page)
        {
            //Tạo biến số sản phẩm trên trang
            int pageSize = 6;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(book.getAllSach_Page().ToPagedList(pageNumber, pageSize));
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
       

    }
}

ClientWebsite/Controllers/SearchController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;

namespace WebSiteBanSach.Controllers
{
    public class SearchController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        // GET: Search
       
        [HttpPost]
        public ActionResult SearchResults(FormCollection f, int? page)
        {
            string sLoai = f["droplist"].ToString();
            string sTuKhoa = f["txtTimKiem"].ToString();
            ViewBag.TuKhoa = sTuKhoa;
            int pageNumber = (page ?? 1);
            int pageSize = 9;

            switch (sLoai)
            {
                // sách
                case "0":
                    List<Sach> lstKQTK = book.SearchSach(sTuKhoa).ToList();
                    List<Sach> lstKQTKGY = book.GetTake3Sach().ToList();
                    if (lstKQTK.Count == 0)
                    {
                        ViewBag.ThongBao = "Không tìm thấy sản phẩm nào";
                        ViewBag.TB = "Sách mới !";
                        return View(lstKQTKGY.ToPagedList(pageNumber, pageSize));
                    }
                    ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
                    return View(lstKQTK.ToPagedList(pageNumber, pageSize));
                //chủ đề
                case "1":
                    List<ClientWebsite.BookService.ChuDe> lstKQCD = book.SearchCD(sTuKhoa).ToList();
                    if(lstKQCD.Count ==0)
                    {
                        ViewBag.ThongBao = "Không tìm thấy kết quả nào !";
                        ViewBag.TB = "Chủ đề gợi ý !";
                        return View("Topics",book.getTake8ChuDe().ToList());
                    }
                    ViewBag.ThongBao = "Đã tìm thấy " + lstKQCD.Count + " kết quả!";
                    return View("Topics", lstKQCD);
                // tác giả
                case "2":
                    List<ClientWebsite.BookService.TacGia> lstKQTG = book.SearchTG(sTuKhoa).ToList();
                    if (lstKQTG.Count == 0)
                    {
                        ViewBag.ThongBao = "Không tìm thấy kết quả nào !";
                        ViewBag.TB = "Tác giả gợi ý !";
                        return View("Authors", book.getTake4TG().ToList());
                    }
                    ViewBag.ThongBao = "Đã tìm thấy " + lstKQTG.Count + " kết quả!";
                    return View("Authors", lstKQTG);
                // nxb
                case "3":
                    List<ClientWebsite.BookService.NhaXuatBan> lstKQNXB = book.SearchNXB(sTuKhoa).ToList();
                    if (lstKQNXB.Count == 0)
                    {
                        ViewBag.ThongBao = "Không tìm thấy kết quả nào !";
                        ViewBag.TB = "Nhà xuất bản gợi ý !";
                        return View("Publisher", book.getTake4NXB().ToList());
                    }
                    ViewBag.ThongBao = "Đã tìm thấy " + lstKQNXB.Count + " kết quả!";
                    return View("Publisher", lstKQNXB);
            }
            
            return View();
        }
        [HttpGet]
        public ActionResult SearchResults(int? page, string sTuKhoa)
        {
            ViewBag.TuKhoa = sTuKhoa;
            List<ClientWebsite.BookService.Sach> lstKQTK = book.SearchSach(sTuKhoa).ToList();
            List<ClientWebsite.BookService.Sach> lstKQTKGY = book.GetTake3Sach().ToList();
            //Phân trang
            int pageNumber = (page ?? 1);
            int pageSize = 9;
            if (lstKQTK.Count == 0)
            {
                ViewBag.ThongBao = "Không tìm thấy kết quả nào !";
                ViewBag.ThongBao = "Sách mới !";
                return View(lstKQTKGY.ToPagedList(pageNumber, pageSize));
            }
            ViewBag.ThongBao = "Đã tìm thấy " + lstKQTK.Count + " kết quả!";
            return View(lstKQTK.OrderBy(n => n.TenSach).ToPagedList(pageNumber, pageSize));
        }
    }
}

ClientWebsite/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

ClientWebsite/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

ClientWebsite/Views/Home/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<ClientWebsite.BookService.Sach>
@{
    ViewBag.Title = "Home";
    List<SelectListItem> list_search = new List<SelectListItem>();
    list_search.Add(new SelectListItem
    {
        Text = "Tên Sách",
        Value = "0"
    });
    list_search.Add(new SelectListItem
    {
        Text = "Chủ Đề",
        Value = "1"
    });
   
    list_search.Add(new SelectListItem
    {
        Text = "Nhà Xuất Bản",
        Value = "3"
    });
}
    <link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <script src="http://code.jquery.com/jquery-1.10.2.js"></script>
    <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
    <link href="~/Content/Tooltips/stickytooltip.css" rel="stylesheet" />
    <script src="~/Content/Tooltips/stickytooltip.js"></script>
<div class="jumbotron">
    <div class="row carousel-holder">

        <div class="row">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner" >
                    <div class="item active" style="text-align:center">
                        <img class="slide-image" src="~/HinhAnh/Anh1.png" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/HinhAnh/Anh2.png" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="~/HinhAnh/Anh3.png" alt="">
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>

    </div>
    
</div>
<!-- Page Heading/Breadcrumbs -->
<div class="row navbar-right">
    <div class="col-md-12">
        <div class="row">
            <div class="input-group" id="adv-search">
                @using (Html.BeginForm("SearchResults", "Search", FormMethod.Post))
                {
                    <table>
                        <tr>
                            <td>
                                @Html.DropDownList("droplist", list_search, htmlAttributes: new { @class = "form-control" })
                            </td>
                            <td>
                                @Html.TextBox("txtTimKiem", "", htmlAttributes: new { @class = "form-control", @placeholder = "Nhập vào từ khóa cần tìm ..." })
                            </td>
                            <td>
                                <button type="submit" class="btn btn-primary"><span class="glyphicon glyphicon-search" aria-hidden="true"></span></button>
                            </td>
                        </tr>
                    </table>
                }

            </div>
        </div>

    </div>
</div>

<div class="row">
    <div class="col-lg-3">
        <ol class="breadcrumb">
            <li class="active">Home</li>
            
        </ol>
        
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        @Html.Action("ToPicPartial", "Topics")
        </div>
    <div class="col-md-9">
        @Html.Action("BookNewiPartial", "Books")
    </div>   
        <div class="col-md-3">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
    <div class="col-md-9">
        <div style="font-size:16pt; font-style:italic"><i class="fa fa-home fa-fw"></i> Danh Mục Sách</div>
        <hr />
        <div class="row">
            @foreach (var item in Model)
            {
                <div class="col-md-4">
                    <a href="@Url.Action("BookDetail", "Books", new { @masach=item.MaSach })">
                        <img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="150" height="150" data-tooltip="@item.MaSach" />
                    </a>
                    <br />
                    @*Dịch dấu chấm động đơn giá sử dụng string.Format("{0:0,0}", tham số)*@
                    <div id="DonGia" style="color:orange; font-size:22px"><font color="Green">Giá:</font> @String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                    <br />
                    @using (Html.BeginForm("ThemGioHang", "Cart", new { @iMaSach = item.MaSach, @strURL = Request.Url.ToString() }))
                    {
                        <input type="submit" style="cursor:pointer;margin-left:10%" value="Cho vào giỏ" class="btn btn-primary btn-danger" />
                        <br />
                        <br />
                    }
                </div>
            }

        </div>
        <div style="clear:both"></div>
        @* Tạo link liên kết các trang*@
        <br /><br />
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
        <div class="MenuTrang">
            <span>@Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))</span>
            <br /><br /><br /><br /><br /><br />
        </div>
    </div>
</div>
<script>
$(function() {
    $( "input[type=submit]" )
      .button()
  });
</script>