ClientWebsite/Controllers/BooksController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;

namespace WebSiteBanSach.Controllers
{
    public class BooksController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        public PartialViewResult BookNewiPartial()
        {
            return PartialView(book.GetTake3Sach().ToList());
        }
        public ViewResult BookDetail(int MaSach = 0)
        {

            Sach sach_detail = book.GetSachById(MaSach);
            if (sach_detail == null)
            {
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            ClientWebsite.BookService.ChuDe chude = book.GetChuDeById(Int32.Parse(sach_detail.MaChuDe.ToString()));
            ClientWebsite.BookService.NhaXuatBan nxb = book.GetNXBByID(Int32.Parse(sach_detail.MaNXB.ToString()));
            ViewBag.TenChuDe = chude.TenChuDe;
            ViewBag.NhaXuatBan = nxb.TenNXB;
            return View(sach_detail);
        }
        public ActionResult AllBooks(int? page)
        {
            int pageSize = 12;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(book.GetSachByMoi().OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }
    }
}

ClientWebsite/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;
using WebSiteBanSach.Models;
using ClientWebsite.OrderService;

namespace WebSiteBanSach.Controllers
{
    public class CartController : Controller
    {
        SachServiceClient sach_client = new SachServiceClient();
        ServiceDonHangClient dh = new ServiceDonHangClient();
        #region Giỏ hàng
        //Lấy giỏ hàng 
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                //Nếu giỏ hàng chưa tồn tại thì mình tiến hành khởi tao list giỏ hàng (sessionGioHang)
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        //Thêm giỏ hàng
        public ActionResult ThemGioHang(int iMaSach, string strURL)
        {
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy ra session giỏ hàng
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sách này đã tồn tại trong session[giohang] chưa
            GioHang sanpham = lstGioHang.Find(n => n.iMaSach == iMaSach);
            if (sanpham == null)
            {
                sanpham = new GioHang(iMaSach);
                //Add sản phẩm mới thêm vào list
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoLuong++;
                return Redirect(strURL);
            }
        }
        //Cập nhật giỏ hàng 
        public ActionResult CapNhatGioHang(int iMaSP, FormCollection f)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sp có tồn tại trong session["GioHang"]
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(f["txtSoLuong"].ToString());

            }
            return RedirectToAction("SuaGioHang");
        }
        //Xóa giỏ hàng
        public ActionResult XoaGioHang(int iMaSP)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaSach == iMaSP);

            }
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        //Xây dựng trang giỏ hàng
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);
        }
        //Tính tổng số lượng và tổng tiền
        //Tính tổng số lượng
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }
        //Tính tổng thành tiền
        private double TongTien()
        {
            double dTongTien = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.ThanhTien);
            }
            return dTongTien;
        }
        //tạo partial giỏ hàng
        public ActionResult CartPartial()
        {
            if (TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        //Xây dựng 1 view cho người dùng chỉnh sửa giỏ hàng
        public ActionResult SuaGioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);

        }
        #endregion
        #region Đặt hàng
        //Xây dựng chức năng đặt hàng
        [HttpPost]
        public ActionResult DatHang()
        {
            //Kiểm tra đăng đăng nhập
            if (Session["InforLogin"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //Kiểm tra giỏ hàng
            if (Session["GioHang"] == null)
            {
                RedirectToAction("Index", "Home");
            }
            //Thêm đơn hàng
            ClientWebsite.OrderService.DonHang ddh = new ClientWebsite.OrderService.DonHang();
            ClientWebsite.UserService.KhachHang kh = (ClientWebsite.UserService.KhachHang)Session["InforLogin"];
            List<GioHang> gh = LayGioHang();
            ddh.MaKH = kh.MaKH;
            ddh.NgayDat = DateTime.Now;
            ddh.NgayGiao = DateTime.Now.AddDays(2);
           
            if (dh.AddDonHang(ddh) != 0)
            {
                Session["TB"] = "Thành Công !";
            }
            //Thêm chi tiết đơn hàng
            double thanhtien = 0;
            foreach (var item in gh)
            {
                ClientWebsite.OrderService.ChiTietDonHang ctDH = new ClientWebsite.OrderService.ChiTietDonHang();
                ctDH.MaDonHang = ddh.MaDonHang;
                ctDH.MaSach = item.iMaSach;
                ctDH.SoLuong = item.iSoLuong;
                ctDH.DonGia = (decimal)item.dDonGia;
                dh.AddCTDonHang(ctDH);
                thanhtien = thanhtien + item.iSoLuong * item.dDonGia;

            }
            return RedirectToAction("GioHang");

        }
        #endregion
       
    }
}

ClientWebsite/Controllers/TopicsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;
using PagedList;

namespace WebSiteBanSach.Controllers
{
    public class TopicsController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        // GET: Topics
        public ActionResult Index()
        {
            return View();
        }
        public PartialViewResult ToPicPartial()
        {
            List<ClientWebsite.BookService.ChuDe> list_cd = book.GetAllCD().ToList();
            return PartialView(list_cd);
        }

        //Sách theo chủ đề
        public ViewResult BooksTopic(int? page,int MaChuDe = 0)
        {
            //Kiểm tra chủ đề tồn tại hay không
            ChuDe cd = book.GetChuDeById(MaChuDe);
            if (cd == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Tạo biến số sản phẩm trên trang
            int pageSize = 6;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            //Truy xuất danh sách các quyển sách theo chủ đề
            List<Sach> lstSach = book.GetSachByMaCD(cd.MaChuDe).ToList();
            if (lstSach.Count == 0)
            {
                ViewBag.Sach = "Không có sách nào thuộc chủ đề này";
            }
            //Gán danh sách chủ để
            ViewBag.lstChuDe = book.GetAllCD().ToList();
            return View(lstSach.ToPagedList(pageNumber, pageSize));
        }
    }
}

ClientWebsite/Views/Topics/BooksTopic.cshtml
@using ClientWebsite.BookService
@using PagedList.Mvc;
@model PagedList.IPagedList<Sach>
@{
    ViewBag.Title = "Books Topic";
    Layout = "~/Views/Shared/_Layout.cshtml";
    int macd=0;
}
<link href="http://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
<script src="http://code.jquery.com/jquery-1.10.2.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<link href="~/Content/Tooltips/stickytooltip.css" rel="stylesheet" />
<script src="~/Content/Tooltips/stickytooltip.js"></script>

@*Gợi ý: có thể copy từ trang index (copy cả link css) thay đối tượng Model bằng lstSach(được gán từ ViewBag.SachTheoChuDe bên trang controller gửi qua)*@
<div class="row">
    <div class="col-md-3">
        @Html.Action("ToPicPartial", "Topics")
    </div>
    <div class="col-md-9">
        <ol class="breadcrumb">
            <li class="active">Books by Topics</li>
        </ol>
    </div>
    <div class="col-md-9" >

        @foreach (var item in Model)
            {
             macd = Int32.Parse(item.MaChuDe.ToString());
            <div class="col-md-4">
                <a href="@Url.Action("BookDetail", "Books", new { @masach=item.MaSach })">
                    <img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="150" height="150" data-tooltip="@item.MaSach" />
                </a>
                <br />
                @*Dịch dấu chấm động đơn giá sử dụng string.Format("{0:0,0}", tham số)*@
                <div id="DonGia" style="color:orange; font-size:22px"><font color="Green">Giá:</font> @String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                <br />
                @using (Html.BeginForm("ThemGioHang", "Cart", new { @iMaSach = item.MaSach, @strURL = Request.Url.ToString() }))
                {
                    <input type="submit" style="cursor:pointer;margin-left:10%" value="Cho vào giỏ" class="btn btn-primary btn-danger" />
                    <br />
                        <br />
                }
            </div>
        }
        <div style="clear:both"></div>
        @* Tạo link liên kết các trang*@
        <br /><br />
        Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
        <div class="MenuTrang">
            <span>@Html.PagedListPager(Model, page => Url.Action("BooksTopic","Topics", new { page = page, MaChuDe= macd }))</span>
            <br /><br /><br /><br /><br /><br />
        </div>
    </div>
    
</div>
<script>
$(function() {
    $( "input[type=submit]" )
      .button()
  });
</script>

ClientWebsite/Views/Topics/ToPicPartial.cshtml
@model List<ClientWebsite.BookService.ChuDe>
<div style="font-size:16pt; font-style:italic">Danh Mục Chủ Đề</div>
<hr />
@foreach (var item in Model)
{
    <a id="btnChuDe" style="width:250px; font-size: 11pt; text-decoration: none" href="@Url.Action("BooksTopic", new {@MaChuDe=item.MaChuDe })" class="button button-submit"> @item.TenChuDe</a><br />
}
<a id="btnChuDe" style="width:250px; font-size: 12pt; color: aliceblue" @*href="@Url.Action("DanhMucChuDe")"*@ class="button button-submit"> Chủ đề khác...</a>
<br />
<div style="clear:both"></div>