ClientWebsite/Controllers/BooksController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;

namespace WebSiteBanSach.Controllers
{
    public class BooksController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        public PartialViewResult BookNewiPartial()
        {
            return PartialView(book.GetTake3Sach().ToList());
        }
        public ViewResult BookDetail(int MaSach = 0)
        {

            Sach sach_detail = book.GetSachById(MaSach);
            if (sach_detail == null)
            {
                //Trả về trang báo lỗi 
                Response.StatusCode = 404;
                return null;
            }
            ClientWebsite.BookService.ChuDe chude = book.GetChuDeById(Int32.Parse(sach_detail.MaChuDe.ToString()));
            ClientWebsite.BookService.NhaXuatBan nxb = book.GetNXBByID(Int32.Parse(sach_detail.MaNXB.ToString()));
            ViewBag.TenChuDe = chude.TenChuDe;
            ViewBag.NhaXuatBan = nxb.TenNXB;
            return View(sach_detail);
        }
        public ActionResult AllBooks(int? page)
        {
            int pageSize = 12;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(book.GetSachByMoi().OrderBy(n => n.GiaBan).ToPagedList(pageNumber, pageSize));
        }
    }
}

ClientWebsite/Controllers/CartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;
using WebSiteBanSach.Models;
using ClientWebsite.OrderService;

namespace WebSiteBanSach.Controllers
{
    public class CartController : Controller
    {
        SachServiceClient sach_client = new SachServiceClient();
        ServiceDonHangClient dh = new ServiceDonHangClient();
        #region Giỏ hàng
        //Lấy giỏ hàng 
        public List<GioHang> LayGioHang()
        {
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang == null)
            {
                //Nếu giỏ hàng chưa tồn tại thì mình tiến hành khởi tao list giỏ hàng (sessionGioHang)
                lstGioHang = new List<GioHang>();
                Session["GioHang"] = lstGioHang;
            }
            return lstGioHang;
        }
        //Thêm giỏ hàng
        public ActionResult ThemGioHang(int iMaSach, string strURL)
        {
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSach);
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy ra session giỏ hàng
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sách này đã tồn tại trong session[giohang] chưa
            GioHang sanpham = lstGioHang.Find(n => n.iMaSach == iMaSach);
            if (sanpham == null)
            {
                sanpham = new GioHang(iMaSach);
                //Add sản phẩm mới thêm vào list
                lstGioHang.Add(sanpham);
                return Redirect(strURL);
            }
            else
            {
                sanpham.iSoLuong++;
                return Redirect(strURL);
            }
        }
        //Cập nhật giỏ hàng 
        public ActionResult CapNhatGioHang(int iMaSP, FormCollection f)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            //Kiểm tra sp có tồn tại trong session["GioHang"]
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                sanpham.iSoLuong = int.Parse(f["txtSoLuong"].ToString());

            }
            return RedirectToAction("SuaGioHang");
        }
        //Xóa giỏ hàng
        public ActionResult XoaGioHang(int iMaSP)
        {
            //Kiểm tra masp
            ClientWebsite.BookService.Sach sach = sach_client.GetSachById(iMaSP);
            //Nếu get sai masp thì sẽ trả về trang lỗi 404
            if (sach == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            //Lấy giỏ hàng ra từ session
            List<GioHang> lstGioHang = LayGioHang();
            GioHang sanpham = lstGioHang.SingleOrDefault(n => n.iMaSach == iMaSP);
            //Nếu mà tồn tại thì chúng ta cho sửa số lượng
            if (sanpham != null)
            {
                lstGioHang.RemoveAll(n => n.iMaSach == iMaSP);

            }
            if (lstGioHang.Count == 0)
            {
                return RedirectToAction("Index", "Home");
            }
            return RedirectToAction("GioHang");
        }
        //Xây dựng trang giỏ hàng
        public ActionResult GioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);
        }
        //Tính tổng số lượng và tổng tiền
        //Tính tổng số lượng
        private int TongSoLuong()
        {
            int iTongSoLuong = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                iTongSoLuong = lstGioHang.Sum(n => n.iSoLuong);
            }
            return iTongSoLuong;
        }
        //Tính tổng thành tiền
        private double TongTien()
        {
            double dTongTien = 0;
            List<GioHang> lstGioHang = Session["GioHang"] as List<GioHang>;
            if (lstGioHang != null)
            {
                dTongTien = lstGioHang.Sum(n => n.ThanhTien);
            }
            return dTongTien;
        }
        //tạo partial giỏ hàng
        public ActionResult CartPartial()
        {
            if (TongSoLuong() == 0)
            {
                return PartialView();
            }
            ViewBag.TongSoLuong = TongSoLuong();
            ViewBag.TongTien = TongTien();
            return PartialView();
        }
        //Xây dựng 1 view cho người dùng chỉnh sửa giỏ hàng
        public ActionResult SuaGioHang()
        {
            if (Session["GioHang"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<GioHang> lstGioHang = LayGioHang();
            return View(lstGioHang);

        }
        #endregion
        #region Đặt hàng
        //Xây dựng chức năng đặt hàng
        [HttpPost]
        public ActionResult DatHang()
        {
            //Kiểm tra đăng đăng nhập
            if (Session["InforLogin"] == null)
            {
                return RedirectToAction("Login", "Account");
            }
            //Kiểm tra giỏ hàng
            if (Session["GioHang"] == null)
            {
                RedirectToAction("Index", "Home");
            }
            //Thêm đơn hàng
            ClientWebsite.OrderService.DonHang ddh = new ClientWebsite.OrderService.DonHang();
            ClientWebsite.UserService.KhachHang kh = (ClientWebsite.UserService.KhachHang)Session["InforLogin"];
            List<GioHang> gh = LayGioHang();
            ddh.MaKH = kh.MaKH;
            ddh.NgayDat = DateTime.Now;
            ddh.NgayGiao = DateTime.Now.AddDays(2);
           
            if (dh.AddDonHang(ddh) != 0)
            {
                Session["TB"] = "Thành Công !";
            }
            //Thêm chi tiết đơn hàng
            double thanhtien = 0;
            foreach (var item in gh)
            {
                ClientWebsite.OrderService.ChiTietDonHang ctDH = new ClientWebsite.OrderService.ChiTietDonHang();
                ctDH.MaDonHang = ddh.MaDonHang;
                ctDH.MaSach = item.iMaSach;
                ctDH.SoLuong = item.iSoLuong;
                ctDH.DonGia = (decimal)item.dDonGia;
                dh.AddCTDonHang(ctDH);
                thanhtien = thanhtien + item.iSoLuong * item.dDonGia;

            }
            return RedirectToAction("GioHang");

        }
        #endregion
       
    }
}

ClientWebsite/Controllers/PublisherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientWebsite.BookService;
using PagedList;

namespace WebSiteBanSach.Controllers
{
    public class PublisherController : Controller
    {
        SachServiceClient book = new SachServiceClient();
        // GET: Publisher
        public PartialViewResult _Publishertial()
        {
            List<ClientWebsite.BookService.NhaXuatBan> list_nxb = book.GetAllNXB().ToList();
            return PartialView(list_nxb);
        }
        public ActionResult BooksbyPublisher(int? page, int MaNXB)
        {
            ViewBag.MANXB = MaNXB;
            //Tạo biến số sản phẩm trên trang
            int pageSize = 6;
            //Tạo biến số trang
            int pageNumber = (page ?? 1);
            return View(book.GetSachByNXB(MaNXB).ToPagedList(pageNumber, pageSize));
        }
        public PartialViewResult Tooltip()
        {
            return PartialView(book.getAllSach_Page().ToList());
        }
    }
}

ClientWebsite/Views/Publisher/BooksbyPublisher.cshtml
@using ClientWebsite.BookService;
@using PagedList.Mvc;
@model PagedList.IPagedList<Sach>
@{
    ViewBag.Title = "BooksbyPublisher";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
    <div class="row">
        <div class="col-md-3">
            @Html.Action("_Publishertial", "Publisher")
        </div>
        <div class="col-lg-9">
            <ol class="breadcrumb">
                <li class="active">Home</li>

            </ol>

        </div>
        @foreach (var item in Model)
            {
            <div class="col-md-3">
                <a href="@Url.Action("BookDetail", "Books", new { @masach=item.MaSach })">
                    <img src="@Url.Content("~/HinhAnhSP/"+item.AnhBia)" width="150" height="150" data-tooltip="@item.MaSach" />
                </a>
                <br />
                @*Dịch dấu chấm động đơn giá sử dụng string.Format("{0:0,0}", tham số)*@
                <div id="DonGia" style="color:orange; font-size:22px"><font color="Green">Giá:</font> @String.Format("{0:0,0}", item.GiaBan) VNĐ</div>
                <br />
                @using (Html.BeginForm("ThemGioHang", "Cart", new { @iMaSach = item.MaSach, @strURL = Request.Url.ToString() }))
                {
                    <input type="submit" style="cursor:pointer;margin-left:10%" value="Cho vào giỏ" class="btn btn-primary btn-danger" />
                        <br />
                        <br />
                }
            </div>
        }
        <div class="col-md-3">
            &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        </div>
        <div class="col-md-9">
            @* Tạo link liên kết các trang*@
            <br /><br />
            Trang @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber)/ @Model.PageCount
            <div class="MenuTrang">
                <span>@Html.PagedListPager(Model, page => Url.Action("BooksbyPublisher", new { page = page, MaNXB = ViewBag.MANXB }))</span>
                <br /><br /><br /><br /><br /><br />
            </div>
        </div>

    </div>
  

ClientWebsite/Views/Publisher/Tooltip.cshtml
@model List<ClientWebsite.BookService.Sach>
<div id="mystickytooltip" class="stickytooltip" style="width:250px">
    @foreach (var item in Model)
    {

        <div id="@item.MaSach" class="atip">
            <div class="tooltiphost">
                <div style="font-weight:bolder"> @item.TenSach</div>
               
                 @item.MoTa
            </div>
        </div>

    }
</div>

ClientWebsite/Views/Publisher/_Publishertial.cshtml
@model List<ClientWebsite.BookService.NhaXuatBan>
<div style="font-size:16pt; font-style:italic">Danh Mục Nhà Xuất Bản</div>
<hr />
@foreach (var item in Model)
{
    <a id="btnChuDe" style="width:250px; font-size: 11pt; text-decoration: none" href="@Url.Action("BooksbyPublisher", new {@MaNXB=item.MaNXB })" class="button button-submit"> @item.TenNXB</a><br />
}
<br />
<div style="clear:both"></div>